export const userConstants = {
    AUTHENTICATE_REQUEST: 'AUTHENTICATE_REQUEST',
    AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
    AUTHENTICATE_FAILURE: 'AUTHENTICATE_FAILURE',
    USERS_LIST_REQUEST: 'USER_REQUEST_LIST',
    USERS_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USERS_LIST_FAILURE: 'USER_LIST_FAILURE',
}